### ISSUE TITLE
Use AllContributors Bot to show off

### ISSUE THREAD

**Issue by SkymanOne** [GeorgeElsham/simpl#4]
https://github.com/apps/allcontributors

**Comment by SkymanOne** [comment]
@all-contributors bot

**Comment by SkymanOne** [comment]
@GeorgeElsham you have to setup it for your account to be used

**Comment by GeorgeElsham** [comment]
I'm going to leave this as the README.md won't change (no more contributors) + I kinda prefer the ✨ minimalistic ✨ style
